---
- hosts: database
  become: yes
  become_user: root
  vars_files:
    - vars/mainmysql.yml
  roles:
    - { role: geerlingguy.mysql }
  tasks:
    #- name: Lancement du playbook mysql_backup
      import_playbook: mysql_backup.yml
   # - name: Lancement du playbook mysql_user
      import_playbook: mysql_user.yml
    #- name: Lancement du playbook mysql_master
      import_playbook: mysql_master.yml
   # - name: Lancement du playbook mysql_slave
      import_playbook: mysql_slave.yml