---
- hosts: database
  become: yes
  become_user: root
  vars_files:
    - vars/client.yml
    - vars/mainmysql.yml
  roles:
    - role: geerlingguy.mysql
  pre_tasks:
    - name: Creation des users mysql
      set_fact:
              mysql_users: "{{ mysql_user | default([])+ [{'name': item.username, 'password': item.password, 'host': item.host, 'priv': item.priv}] }}"
      with_items: "{{ clients }}"