---
- hosts: database
  become: yes
  become_user: root
  vars_files:
    - vars/client.yml
    - vars/mainmysql.yml
  roles:
    - role: geerlingguy.mysql
  pre_tasks:
    - name: Génération de la configuration des bases pour geerlingguy depuis nos client
      set_fact:
              mysql_databases: " {{ mysql_databases | default([])+ [{'name': item.database, 'encoding': latin1, 'collation': latin1_general_ci}] }}"
      with_items: "{{ clients }}"
    - name: debug la variable database précemment créée
      debug:
         msg: "{{mysql_databases}}"
    - name: Géneration de la configuration pour geerlingguy.mysql depuis notre base client
      set_fact:
              mysql_users: "{{ mysql_users | default([])+ [{'name': item.username, 'password': item.password, 'host': item.host, 'priv': item.priv}] }}"
      with_items: "{{ clients }}"
    - name: debug la variable précemment créée
      debug:
         msg: "{{mysql_users}}"
