---
- hosts: database
  become: yes
  vars_files:
    - vars/mainmysql.yml
  roles:
    - { role: geerlingguy.mysql }
  tasks:
    - name: Lancement du playbook mysql_backup
      import_playbook: mysql_backup.yml
    - name: Lancement du playbook mysql_user
      import_playbook: mysql_user.yml