---
- hosts: databases
  become: yes
  become_user: root
  roles:
  - role: ansible-role-mysql-backup-master
    mysql_backup_dir: /vars/backups/databases
    mysql_backup_filename_format: "{{ ansible_hostname }}-%Y%m%d.sql.gz"
    mysql_backup_minimum_expected_size: 100000