---
- hosts: database
  become: yes
  tasks:
    - name: Creation de la réplication du master
      set_fact:
              mysql_server_id: "2"
              mysql_max_binlog_size: "100M"
              mysql_binlog_format: "ROW"
              mysql_expire_logs_days: "10"
              mysql_replication_role: 'slave'
              mysql_replication_master: ''
              mysql_replication_user: { repuser }