---
- name: Add fichier host
  blockinfile:
    path: /etc/hosts
    block: |
          192.168.23.185 database_master
          192.168.23.184 database_slave
          192.168.23.181 webserver1
          192.168.23.186 client1


