---
- name: Add user itesciadmin
  user:
            name: "{{item.name}}"
            password: "{{item.password}}"
            #  loop: "{{utilisateur}}"
   #        name: "nouveaucompte"
   #        password: '*'
            groups:
                  - sudo
                  - itescia
            state: present
            createhome: yes
            home: /home/"{{item.name}}"
  loop: "{{utilisateur}}"
