galaxy_info:
  author: ome-devel@lists.openmicroscopy.org.uk
  description: Setup a cron job for regular full Mysql/Mariadb database dumps
  company: Open Microscopy Environment
  license: BSD
  min_ansible_version: 2.1
  platforms:
  - name: EL
    versions:
    - 7
  role_name: mysql_backup
  galaxy_tags: []

dependencies: []
